name: Build UEFI for release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
env:
  CI_BUILD: true
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build UEFI
        run: bash ./setup_env.sh -p apt && bash ./build_uefi.sh -d pipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          # run: ./build_uefi.sh -d gts8 -m 8
          path: ./*.img
